/*
 * led_hardward_config.h
 *
 *  Created on: Mar 8, 2014
 *      Author: TV
 */

#ifndef GPIO_CONFIG_H_
#define GPIO_CONFIG_H_

//gpio_pinName

typedef enum {
	MCU_BQ_8=0,
	MCU_BQ_7,
	MCU_BQ_6,
	MCU_BQ_5,
	MCU_BQ_4,
	MCU_BQ_3,
	MCU_BQ_2,
	MCU_BQ_1,
	MCU_VN_5,
	MCU_VN_4,
	MCU_VN_3,
	MCU_VN_2,
	MCU_VN_1,
	PORT_BUTTON1,
	PORT_BUTTON2,
	MCU_S_4,
	MCU_S_3,
	MCU_S_2,
	MCU_S_1,
	MCU_VT_6,
	MCU_VT_5,
	MCU_VT_4,
	MCU_VT_3,
	MCU_VT_2,
	MCU_VT_1,
	MCU_C2,
	MCU_C1,
	NUMBER_DIGITAL
} GPIO_PINNAME;

#if	defined(__GPIO_DIGITAL_DRV)

typedef struct {
	GPIO_TypeDef * type_def; //GPIOA,GPIOB,GPIOC,GPIOD,GPIOE,
							 //GPIOF,GPIOG
	GPIO_InitTypeDef init_st;
}GPIO_CONFIG_ST;
/*
 * @Digital pin configurations
 * */
const GPIO_CONFIG_ST gpio_conf_st[NUMBER_DIGITAL] = {
	{	GPIOA,{	GPIO_PIN_0, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_1, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_2, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_3, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_4, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_5, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_6, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_7, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_8, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_9, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_10, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_11, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_12, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	
	{	GPIOB,{	GPIO_PIN_0, GPIO_MODE_INPUT, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOB,{	GPIO_PIN_1, GPIO_MODE_INPUT, GPIO_NOPULL,GPIO_SPEED_LOW,} },



	{	GPIOB,{	GPIO_PIN_5, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOB,{	GPIO_PIN_6, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOB,{	GPIO_PIN_7, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOB,{	GPIO_PIN_8, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },

	{	GPIOB,{	GPIO_PIN_10, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOB,{	GPIO_PIN_11, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOB,{	GPIO_PIN_12, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOB,{	GPIO_PIN_13, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOB,{	GPIO_PIN_14, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOB,{	GPIO_PIN_15, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	
	
	{	GPIOB,{	GPIO_PIN_3, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
	{	GPIOA,{	GPIO_PIN_15, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL,GPIO_SPEED_LOW,} },
};
#endif

#endif /* LED_HARDWARD_CONFIG_H_ */
